### ISSUE TITLE
Adding Mac ARM support

### ISSUE THREAD

**Issue by tresf** [qzind/tray#591]
TODO:

* [x] Update and test JNA 5.6.0 (Done via #732)
* [x] Update upstream JNA to support Apple Silicon (https://github.com/java-native-access/jna/pull/1238)
* [x] Bump JNA to 5.7.0, with `darwin-aarch64` support  (Done via #757, #783)
* [x] Update HID4Java to support Apple Silicon (https://github.com/gary-rowe/hid4java/issues/108)
* [x] Update JSSC to support Apple Silicon (https://github.com/java-native/jssc/issues/74)
* [x] Update JavaFX to support Apple Silicon (tracked privately `SUPQZ-7`)
   * Done via #783, but buggy, only `{rasterize: false}` works reliably

... Somewhat related: https://github.com/Homebrew/homebrew-core/pull/65670

---

What works through emulation:
* AdoptOpenJDK11 installtaion
* QZ Tray 2.1.1 installation
* PDFWriter installation
* Printing PDFs
* Listing serial ports
* Listing HID ports

What doesn't work through emulation:
* [x] About Page (Backtrace is thrown during JNA call, see #683) (Fixed inadvertently via https://github.com/qzind/tray/pull/685, and on ARM via https://github.com/qzind/tray/commit/6b1ec5e029fc79990f4a28ebd9734c4236f9608d)
* [x] HTML Printing (Backtrace is thrown during a JNI call)

---

**Original Post**

<details>
<summary>Click to expand</summary>

The rumors of Apple switching to ARM are getting stronger...

https://9to5mac.com/2020/02/24/apple-to-release-first-arm-mac-without-intel-processor-in-next-18-months-predicts-kuo/

> Ming-Chi Kuo is out with a new analyst note today and the most interesting part of his forecast is that Apple will release its first Mac with an ARM processor in the first half of 2021.

This is a fairly short amount of time to create a build with ARM support especially considering there's currently no ARM Java SDK out for Java making a runtime a non-starter.

Apple may find a way to emulate the x86 instruction set to buy us some time, but it would have to be x86-64 since Catalina dropped support for 32-bit applications.

To support this, well need either:
1. A way of creating either a universal installer<br>-- or --
2. ARM platform detection on our downloads page

White-Label builds will be directly impacted as we currently leverage an x86-64 Mac to build for all platforms.

</details>

**Comment by tresf** [comment]
The rumors have come true and Apple has confirmed the following:

* Rosetta 2: x86_64 emulation layer for non-native apps
* Universal 2: Dual x86_64 + ARM binary format

The good news is the current x86_64 version of Java will run as-is through hardware emulation according to claims by Apple.  This is actually better than the situation with Windows (#605) where emulation is limited to 32-bit apps only.

In order to test the new Mac, a company needs to be enrolled into the early developer program.  If accepted, the company receives a loaner Mac Mini equipped with MacOS "Big Sur", an Apple A12Z CPU, 16 GB RAM, 512 GB SSD.  The loaner must be returned to Apple at the end of the program.

If we're not accepted into this program, we'll have to lend a machine from someone who is, or wait for a consumer release of the new hardware.

FWIW, Apple's coining the hardware as "Apple Silicon", not ARM.

**Comment by tresf** [comment]
FYI, pinged HID4Java: https://github.com/gary-rowe/hid4java/issues/93

**Comment by gary-rowe** [comment]
Quick update: I've released version 0.6.0 to Maven Central which has several improvements to JNA and `hidapi`. 

In the examples code I've added an architecture detection logging message which should assist with selection of suitable ARM support. As I understand it, JNA supports `linux-arm` (32-bit hard float), `linux-armel` (32-bit EABI) and `linux-aarch64` is directed at ARM v8 but I don't have any hardware that could trigger this detection.

Would it be possible for your team to run the `0.6.0` code on the ARM hardware and tell me what the platform output is? For example on OS X (10.15.5) the output is:

```
Platform architecture: x86-64
Resource prefix: darwin
```

**Comment by tresf** [comment]
> Quick update: I've released version 0.6.0 to Maven Central which has several improvements to JNA and hidapi.Quick update: I've released version 0.6.0 to Maven Central which has several improvements to JNA and hidapi.
> 
> In the examples code I've added an architecture detection logging message which should assist with selection of suitable ARM support. As I understand it, JNA supports linux-arm (32-bit hard float), linux-armel (32-bit EABI) and linux-aarch64 is directed at ARM v8 but I don't have any hardware that could trigger this detection.
> 
> Would it be possible for your team to run the 0.6.0 code on the ARM hardware and tell me what the platform output is? For example on OS X (10.15.5) the output is:
> 
> Platform architecture: x86-64
Resource prefix: darwin
In the examples code I've added an architecture detection logging message which should assist with selection of suitable ARM support. As I understand it, JNA supports linux-arm (32-bit hard float), linux-armel (32-bit EABI) and linux-aarch64 is directed at ARM v8 but I don't have any hardware that could trigger this detection.
> 
> Would it be possible for your team to run the 0.6.0 code on the ARM hardware and tell me what the platform output is? For example on OS X (10.15.5) the output is:
> 
> ```
> Platform architecture: x86-64
> Resource prefix: darwin
> ```

@gary-rowe it seems some GitHub comments got rolled back (possibly due to service outages?).  One major issue with ARM on Mac in general is that AFAIK there's no binaries yet, so Java will execute using the Intel x86_64 instruction set under Coretto 2 emulation.  I'd be happy to run some code, but I fear that the values should match that of your 10.15.5 results unless they're running natively, no?

**Comment by gary-rowe** [comment]
> it seems some GitHub comments got rolled back (possibly due to service outages?).

Nope that was me posting to the wrong project and covering my tracks. See [gary-rowe/hid4java#93](https://github.com/gary-rowe/hid4java/issues/93).

> One major issue with ARM on Mac in general is that AFAIK there's no binaries yet, so Java will execute using the Intel x86_64 instruction set under Coretto 2 emulation. I'd be happy to run some code, but I fear that the values should match that of your 10.15.5 results unless they're running natively, no?

It does seem as if that would be the case based on emulation. I was thinking you had some pre-release hardware running the binaries you could use for experimentation. Let me know when you're in position to move forward with this and I'll do what I can to help.

**Comment by tresf** [comment]
> I was thinking you had some pre-release hardware running the binaries you could use for experimentation.

I do, and I'd be happy to run tests, but at time of writing this `openjdk` isn't working yet.  I've reached out to a few channels to see if perhaps we can at least get a [zero-build](https://openjdk.java.net/projects/zero/) for starters.

**Comment by gary-rowe** [comment]
> I do, and I'd be happy to run tests, but at time of writing this openjdk isn't working yet. I've reached out to a few channels to see if perhaps we can at least get a zero-build for starters.

OK. Just give me the nod when you're ready.

**Comment by tresf** [comment]
> I do, and I'd be happy to run tests, but at time of writing this openjdk isn't working yet. I've reached out to a few channels to see if perhaps we can at least get a zero-build for starters.

Sorry, I realized now that this is a bit specific since I've separated Windows and ARM bug reports.  I do have a JDK on Windows ARM, so I can get values from that soon.  I'll post them on the more broad bug report here: https://github.com/gary-rowe/hid4java/issues/93

**Comment by tresf** [comment]
FYI: JNA PR to help support this change: https://github.com/java-native-access/jna/pull/1238

**Comment by tresf** [comment]
> OK. Just give me the nod when you're ready.

@gary-rowe, JNA is available [in snapshot](https://groups.google.com/g/jna-users/c/UwUa5qWbIco/m/AMLX8FNlAQAJ) form and openjdk has been ported to ARM64 and is readily available for testing, so we're ready to begin testing as soon as there's a build available.

**Comment by tresf** [comment]
Initial support has landed on master (via https://github.com/qzind/tray/pull/783)

What works natively:
* :white_check_mark: JNA
* :white_check_mark: JavaFX (but ONLY using `{ rasterize: true }`, Monocle disabled)

What doesn't work:
* :no_entry_sign: JavaFX (`{ rasterize: false }` will fail after the 1st attempt, reported upstream `SUPQZ-7`)
* :no_entry_sign: JSSC (we maintain this now, waiting on us)
* :no_entry_sign: HID4Java (requires upstream JNA bump, or we could just build this ourself)

**Comment by tresf** [comment]
Support has landed on master branch.  Downloads will be up soon (days, not weeks).

Note, QZ Tray doesn't know the difference between a Rosetta 2 version of Java or a native version, so it's not yet intelligent enough to automatically run natively in environments with both Java versions installed.

Until QZ Tray 2.1.4 is published, we have a dedicated ARM64 installer available here:
https://github.com/tresf/tray/releases/tag/v2.1.4-RC

If you have any issues with this release, please open a new bug report.

**Comment by tresf** [comment]
M1 downloads are available https://qz.io/download
